# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fae70e573a20314fc9e7e7d00c27eedefdc74d8cc649d53d7c50c3d7163968101b54e9a36400a2f39fd566a6648c2dce31a03f5b46b447f6355a2961fe9a07e

test:
  secret_key_base: e9a5bc348142dc98ae725e83e52dea2b4e0938b27a46b09989ff3d33b62db32e8344cb909e4a6b288823b4040ef7fb8cf1fcd71165a683e6b3b5985efdd4c04b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
